:: MSVC is preferred.
set CC=cl.exe
set CXX=cl.exe

mkdir build
cd build
cmake ^
    -G "Ninja" ^
    -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% ^
    -DCMAKE_BUILD_TYPE=Release ^
    -DOGRE_BUILD_DEPENDENCIES=OFF ^
    -DOGRE_BUILD_SAMPLES=OFF ^
    -DOGRE_BUILD_TESTS=OFF ^
    -DOGRE_BUILD_TOOLS=OFF ^
    -DOGRE_BUILD_MSVC_MP=ON ^
    -DOGRE_BUILD_MSVC_ZM=ON ^
    -DOGRE_INSTALL_DEPENDENCIES=OFF ^
    -DOGRE_INSTALL_DOCS=OFF ^
    -DOGRE_INSTALL_PDB=OFF ^
    -DOGRE_INSTALL_SAMPLES=OFF ^
    -DOGRE_INSTALL_TOOLS=OFF ^
    -DOGRE_INSTALL_CMAKE=ON ^
    -DOGRE_INSTALL_VSPROPS=OFF ^
    -DOGRE_STATIC=OFF ^
    -DOGRE_CONFIG_THREAD_PROVIDER=std ^
    -DOGRE_BUILD_RENDERSYSTEM_D3D11=ON ^
    -DOGRE_BUILD_RENDERSYSTEM_GL=ON ^
    -DOGRE_BUILD_RENDERSYSTEM_GL3PLUS=ON ^
    -DOGRE_BUILD_RENDERSYSTEM_GLES=OFF ^
    -DOGRE_BUILD_RENDERSYSTEM_GLES2=OFF ^
    %SRC_DIR%
if errorlevel 1 exit 1

:: Install.
cmake --build . --config Release --target install
if errorlevel 1 exit 1
