{% set name = "winpcap" %}
{% set version = "4.1.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://www.winpcap.org/install/bin/WpcapSrc_{{ version.replace('.', '_') }}.zip
    sha256: 346a93f6b375ac4c1add5c8c7178498f1feed4172fb33383474a91b48ec6633a

build:
  number: 0
  skip: true  # [not win]
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}              # [not win]
    - {{ compiler('c') }}                # [not win]
    - vs2017_win-64                      # [win64]
    - vs2017_win-32                      # [win32]

test:
  commands:
    - uncrustify --version

about:
  home: https://www.winpcap.org/
  license: BSD-3-Clause
  license_family: BSD
  summary: |
    WinPcap is an open source library for packet capture and network analysis for the Win32 platforms.

extra:
  recipe-maintainers:
    - seanyen
